define([], function() {
  return {
    "PropertyPaneDescription": "Configure the Guest Sponsor Info web part.",
    "BasicGroupName": "Settings",
    "TitleFieldLabel": "Title",
    "LoadingMessage": "Loading your sponsors…",
    "NoSponsorsMessage": "No sponsors found for your account.",
    "SponsorUnavailableMessage": "Your sponsor/owner is no longer available. Please contact your project stakeholder to have a new sponsor/owner assigned to your account.",
    "ErrorMessage": "Could not load sponsor information. Please try again later.",
    "EditModePlaceholder": "Guest Sponsor Info — switch to view mode to see sponsors.",
    "GuestOnlyPlaceholder": "This web part is only visible to guest users in view mode.",
    "MockModeFieldLabel": "Demo mode (mock data)",
    "MockModePlaceholder": "Guest Sponsor Info — Demo mode active. Switch to view mode to see mock sponsors.",

    "PresenceAvailable": "Available",
    "PresenceAvailableIdle": "Available, Idle",
    "PresenceAway": "Away",
    "PresenceBeRightBack": "Be Right Back",
    "PresenceBusy": "Busy",
    "PresenceBusyIdle": "Busy, Idle",
    "PresenceDoNotDisturb": "Do Not Disturb",
    "PresenceInAMeeting": "In a meeting",
    "PresenceInACall": "In a call",
    "PresencePresenting": "Presenting",
    "PresenceFocusing": "Focusing",
    "PresenceOutOfOffice": "Out of office",
    "PresenceOutOfOfficeSuffix": ", out of office",
    "PresenceOffline": "Offline",

    "ContactDetailsAriaLabel": "Contact details for {0}",
    "ContactActionsAriaLabel": "Contact actions",
    "ChatTitle": "Chat in Microsoft Teams",
    "EmailTitle": "Send email",
    "CallTitle": "Audio call in Microsoft Teams",
    "ChatLabel": "Chat",
    "EmailLabel": "Email",
    "CallLabel": "Call",

    "ContactInfoSection": "Contact information",
    "EmailFieldLabel": "Email",
    "WorkPhoneFieldLabel": "Work phone",
    "MobileFieldLabel": "Mobile",
    "WorkLocationFieldLabel": "Work location",

    "OrganizationSection": "Organization",
    "ManagerLabel": "Manager",

    "CopiedFeedback": "Copied!",
    "CopyEmailAriaLabel": "Copy email address",
    "CopyWorkPhoneAriaLabel": "Copy work phone",
    "CopyMobileAriaLabel": "Copy mobile number",
    "CopyLocationAriaLabel": "Copy work location",

    "TeamsAccessPendingTitle": "Microsoft Teams not set up yet",
    "TeamsAccessPendingMessage": "Your guest access to Microsoft Teams in this organization hasn\u2019t been set up yet. This doesn\u2019t affect your own Teams account. Ask your sponsor to add you to a Team \u2014 once they do, Teams features like chat, calls, and meetings will become available here.",
    "TeamsNotReadyChatTooltip": "Chat not available in this organization \u2014 your Teams guest access hasn\u2019t been set up yet",
    "TeamsNotReadyCallTooltip": "Call not available in this organization \u2014 your Teams guest access hasn\u2019t been set up yet",

    "DisplayGroupName": "Display",
    "ShowBusinessPhonesFieldLabel": "Show business phone numbers",
    "ShowMobilePhoneFieldLabel": "Show mobile phone number",
    "ShowWorkLocationFieldLabel": "Show work location",
    "ShowManagerFieldLabel": "Show manager",
    "UseInformalAddressFieldLabel": "Use informal address",

    "FunctionGroupName": "Azure Function",
    "FunctionUrlFieldLabel": "Sponsor API URL (Azure Function)",
    "FunctionClientIdFieldLabel": "Sponsor API Client ID (Azure Function App Registration)",
    "ProxyStatusChecking": "Checking Azure Function connection\u2026",
    "ProxyStatusOk": "Azure Function reachable",
    "ProxyStatusError": "Azure Function not reachable",
    "ShowSponsorJobTitleFieldLabel": "Show sponsor's job title",
    "ShowManagerJobTitleFieldLabel": "Show manager's job title",
    "ShowSponsorDepartmentFieldLabel": "Show sponsor's department",
    "ShowManagerDepartmentFieldLabel": "Show manager's department",
    "DepartmentLabel": "Department",
    "ShowCityFieldLabel": "Show city",
    "ShowCountryFieldLabel": "Show country",
    "CityFieldLabel": "City",
    "CountryFieldLabel": "Country",
    "CopyCityAriaLabel": "Copy city",
    "CopyCountryAriaLabel": "Copy country"
  }
});
