define([], function() {
  return {
    "PropertyPaneDescription": "Määritä Vieraan sponsoritiedot -verkko-osa.",
    "BasicGroupName": "Asetukset",
    "TitleFieldLabel": "Otsikko",
    "LoadingMessage": "Ladataan sponsoreitasi…",
    "NoSponsorsTitle": "Ei sponsoreita",
    "NoSponsorsMessage": "Tilillesi ei löydy sponsoreita.",
    "SponsorUnavailableTitle": "Sponsori ei käytettävissä",
    "SponsorUnavailableMessage": "Sponsorisi ei ole enää käytettävissä. Ota yhteyttä projektipäällikköön, jotta tilillesi voidaan nimeätä uusi sponsori.",
    "ErrorMessageTitle": "Jokin meni pieleen",
    "ErrorMessage": "Sponsoritietojen lataaminen epäonnistui. Yritä myöhemmin uudelleen.",
    "EditModePlaceholder": "Vieraan sponsoritiedot — siirry näyttötilaan nähdäksesi sponsorit.",
    "GuestOnlyPlaceholder": "Tämä verkko-osa näkyy vain vieraskäyttäjille näyttötilassa.",
    "MockModeFieldLabel": "Demotila (testitiedot)",
    "MockModePlaceholder": "Vieraan sponsoritiedot — Demotila on aktiivinen. Siirry näyttötilaan nähdäksesi testitiedot.",
    "MockTeamsUnavailableFieldLabel": "Simuloi Teamsin saatavuuseste",

    "PresenceAvailable": "Saatavilla",
    "PresenceAvailableIdle": "Saatavilla, poissaoleva",
    "PresenceAway": "Poissa",
    "PresenceBeRightBack": "Palaan pian",
    "PresenceBusy": "Varattu",
    "PresenceBusyIdle": "Varattu, poissaoleva",
    "PresenceDoNotDisturb": "Älä häiritse",
    "PresenceInAMeeting": "Kokouksessa",
    "PresenceInACall": "Puhelussa",
    "PresencePresenting": "Esittää",
    "PresenceFocusing": "Keskittymistilassa",
    "PresenceOutOfOffice": "Poissa toimistosta",
    "PresenceOutOfOfficeSuffix": ", poissa toimistosta",
    "PresenceOffline": "Offline",

    "ContactDetailsAriaLabel": "{0} yhteystiedot",
    "ContactActionsAriaLabel": "Yhteydenottomahdollisuudet",
    "ChatTitle": "Aloita chat – {name}",
    "EmailTitle": "Sähköposti – {name}",
    "CallTitle": "Aloita äänipuhelu – {name}",
    "ChatLabel": "Chatti",
    "EmailLabel": "Sähköposti",
    "CallLabel": "Soita",

    "ContactInfoSection": "Yhteystieto",
    "EmailFieldLabel": "Sähköposti",
    "WorkPhoneFieldLabel": "Työpuhelin",
    "MobileFieldLabel": "Matkapuhelin",
    "WorkLocationFieldLabel": "Työpaikka",
    "AddressFieldLabel": "Osoite",
    "StreetAddressFieldLabel": "Katu",
    "PostalCodeFieldLabel": "Postinumero",
    "StateFieldLabel": "Osavaltio/alue",

    "OrganizationSection": "Organisaatio",
    "ReportsToSection": "Raportoi henkilölle",
    "ManagerLabel": "Esimies",

    "CopiedFeedback": "Kopioitu!",
    "CopyEmailAriaLabel": "Kopioi sähköpostiosoite",
    "CopyWorkPhoneAriaLabel": "Kopioi työpuhelin",
    "CopyMobileAriaLabel": "Kopioi matkapuhelinnumero",
    "CopyLocationAriaLabel": "Kopioi työpaikka",
    "CopyAddressAriaLabel": "Kopioi osoite",
    "CopyStreetAddressAriaLabel": "Kopioi katu",
    "CopyPostalCodeAriaLabel": "Kopioi postinumero",
    "CopyStateAriaLabel": "Kopioi osavaltio/alue",
    "AddressMapSectionLabel": "Kartan esikatselu",
    "AddressMapLoadingLabel": "Ladataan kartan esikatselua...",
    "OpenAddressInMapLabel": "Avaa kartassa",

    "TeamsAccessPendingTitle": "Microsoft Teamsia ei ole vielä määritetty",
    "TeamsAccessPendingMessage": "Vierasoikeuksiasi Microsoft Teamsiin tässä organisaatiossa ei ole vielä määritetty. Tämä ei vaikuta omaan Teams-tiliisi. Pyydä sponsoriasi lisäämään sinut tiimiin — sen jälkeen Teams-toiminnot kuten chat, puhelut ja kokoukset ovat käytettävissä täällä.",
    "TeamsNotReadyChatTooltip": "Chat ei käytettävissä täällä — Teams-vierasoikeuksiasi ei ole vielä määritetty",
    "TeamsNotReadyCallTooltip": "Puhelu ei käytettävissä täällä — Teams-vierasoikeuksiasi ei ole vielä määritetty",

    "VersionMismatchTitle": "Päivitys saatavilla",
    "VersionMismatchMessage": "Verkko-osalle on saatavana päivitys. Pyydä järjestelmänvalvojaasi varmistamaan, että verkko-osa ja Azure Function käyttävät samaa versiota.",
    "InsufficientPermissionsTitle": "Lupa puuttuu",
    "InsufficientPermissionsMessage": "Sponsoritietoja ei voitu ladata — vaadittua palvelulupaa ei ole myönnetty. Ota yhteyttä IT-järjestelmänvalvojaasi.",

    "DisplayGroupName": "Näyttö",
    "CardLayoutFieldLabel": "Kortin asettelu",
    "CardLayoutAutoOption": "Automaattinen",
    "CardLayoutFullOption": "Täysi",
    "CardLayoutCompactOption": "Tiivis",
    "ShowBusinessPhonesFieldLabel": "Näytä työpuhelin",
    "ShowMobilePhoneFieldLabel": "Näytä matkapuhelin",
    "ShowWorkLocationFieldLabel": "Näytä työpaikka",
    "ShowManagerFieldLabel": "Näytä esimies",
    "UseInformalAddressFieldLabel": "Käytä sinuttelumuotoa",
    "UseInformalAddressHint": "Vaikuttaa tilaviesteihin ja banneihin, jotka puhuttelevat vieraskäyttäjää suoraan kokonaisin lausein (esim. virheilmoitukset, Teams-pääsy-ilmoitus).",

    "ShowWorkLocationFallbackFieldLabel": "Näytä työpaikka varana",
    "LocationDisplayHintGeoWithFallback": "Kaupunki ja maa yhdistetään yhdeksi maantieteelliseksi riviksi. Työpaikka näytetään vain, jos kaupunki-/maatietoja ei ole saatavilla.",
    "LocationDisplayHintGeoOnly": "Kaupunki ja maa yhdistetään yhdeksi maantieteelliseksi riviksi. Työpaikka on piilotettu.",
    "LocationDisplayHintOfficeOnly": "Vain työpaikka näytetään. Ota kaupunki ja/tai maa käyttöön, jotta näytetään maantieteellinen rivi.",
    "LocationDisplayHintHidden": "Kaikki sijainti- ja osoitekentät ovat piilotettu.",
    "LocationDisplayHintSeparateRows": "Käytössä olevat osoitekentät yhdistetään yhdeksi klikattavaksi riviksi.",
    "AdvancedDisplayGroupName": "Lisänäyttöasetukset",
    "ManagerOptionsDisabledHint": "Ota esimiehen näyttö käyttöön, jotta voit määrittää esimieskohtaiset kentät.",
    "FunctionGroupName": "Azure-funktio",
    "FunctionUrlFieldLabel": "Azure-funktion perus-URL",
    "FunctionClientIdFieldLabel": "Sponsori-API-asiakas-ID (Azure-funktiosovelluksen rekisteröinti)",
    "ProxyStatusChecking": "Tarkistetaan Azure-funktiota…",
    "ProxyStatusOk": "Azure-funktio tavoitettavissa",
    "ProxyStatusError": "Azure-funktiota ei löydy",
    "AuthorSectionGroupName": "Tietoa julkaisijasta",
    "AuthorSectionIntro": "Workoho GmbH: konsultointia turvalliseen ja skaalautuvaan M365-yhteistyöhön.",
    "AuthorSectionWebsiteLinkLabel": "Ota yhteyttä Workohoon konsultointia varten",
    "AuthorSectionConsultingText": "Autamme governance-asioissa, B2B-vieraskäytössä, identiteeteissä ja yhteistyöprosesseissa, jotta yhteistyö pysyy turvallisena, auditoitavana ja tehokkaana.",
    "AuthorSectionPartnerPrefix": "Workoho on",
    "AuthorSectionPartnerLinkLabel": "EasyLife 365",
    "AuthorSectionPartnerSuffix": "Platinum-jälleenmyyntikumppani.",
    "AuthorSectionPartnerTagline": "EasyLife 365:n avulla automatisoit käyttöoikeusprosessit ja tuot järjestyksen monimutkaisiin Microsoft 365 -ympäristöihin.",
    "AuthorSectionSourceCodeLabel": "Lähdekoodi GitHubissa",
    "AuthorSectionVersionLabel": "Web-osan versio",
    "ShowSponsorJobTitleFieldLabel": "Näytä sponsorin tehtävänimike",
    "ShowManagerJobTitleFieldLabel": "Näytä esihenkilön tehtävänimike",
    "ShowSponsorDepartmentFieldLabel": "Näytä sponsorin osasto",
    "ShowManagerDepartmentFieldLabel": "Näytä esihenkilön osasto",
    "DepartmentLabel": "Osasto",
    "ShowCityFieldLabel": "Näytä kaupunki",
    "ShowCountryFieldLabel": "Näytä maa",
    "ShowStreetAddressFieldLabel": "Näytä katu",
    "ShowPostalCodeFieldLabel": "Näytä postinumero",
    "ShowStateFieldLabel": "Näytä osavaltio/alue",
    "AzureMapsSubscriptionKeyFieldLabel": "Azure Maps -tilaavain",
    "ExternalMapProviderFieldLabel": "Karttapalvelu",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "MapProviderNoneOption": "Poistettu käytöstä (ei karttaostaman)",
    "AddressMapProviderHint": "Jotta kartta voi löytää sijainnin, valitse vähintään kaupunki tai maa yhdessä muiden osoitekenttien kanssa.",
    "CityFieldLabel": "Kaupunki",
    "CountryFieldLabel": "Maa",
    "CopyCityAriaLabel": "Kopioi kaupunki",
    "CopyCountryAriaLabel": "Kopioi maa",
    "ShowPresenceFieldLabel": "Näytä läsnäolotila",
    "ShowSponsorPhotoFieldLabel": "Näytä sponsorin kuva",
    "ShowManagerPhotoFieldLabel": "Näytä esihenkilön kuva",
  }
});
