define([], function() {
  return {
    "PropertyPaneDescription": "Configurer le composant WebPart \u00abInfos sur le sponsor invit\u00e9\u00bb.",
    "BasicGroupName": "Param\u00e8tres",
    "TitleFieldLabel": "Titre",
    "LoadingMessage": "Chargement de vos sponsors\u2026",
    "NoSponsorsMessage": "Aucun sponsor trouv\u00e9 pour votre compte.",
    "SponsorUnavailableMessage": "Votre sponsor/propri\u00e9taire n\u2019est plus disponible. Veuillez contacter votre responsable de projet pour qu\u2019un nouveau sponsor/propri\u00e9taire vous soit attribu\u00e9.",
    "ErrorMessage": "Impossible de charger les informations sur les sponsors. Veuillez r\u00e9essayer ult\u00e9rieurement.",
    "EditModePlaceholder": "Infos sur le sponsor invit\u00e9 \u2014 passez en mode d\u2019affichage pour voir les sponsors.",
    "GuestOnlyPlaceholder": "Ce composant WebPart n\u2019est visible qu\u2019aux utilisateurs invit\u00e9s en mode d\u2019affichage.",
    "MockModeFieldLabel": "Mode d\u00e9mo (donn\u00e9es fictives)",
    "MockModePlaceholder": "Infos sur le sponsor invit\u00e9 \u2014 Mode d\u00e9mo actif. Passez en mode d\u2019affichage pour voir les donn\u00e9es fictives.",

    "PresenceAvailable": "Disponible",
    "PresenceAvailableIdle": "Disponible, inactif",
    "PresenceAway": "Absent",
    "PresenceBeRightBack": "De retour dans un instant",
    "PresenceBusy": "Occup\u00e9",
    "PresenceBusyIdle": "Occup\u00e9, inactif",
    "PresenceDoNotDisturb": "Ne pas d\u00e9ranger",
    "PresenceInAMeeting": "En r\u00e9union",
    "PresenceInACall": "En appel",
    "PresencePresenting": "En pr\u00e9sentation",
    "PresenceFocusing": "En concentration",
    "PresenceOutOfOffice": "Absent du bureau",
    "PresenceOutOfOfficeSuffix": ", absent du bureau",
    "PresenceOffline": "Hors connexion",

    "ContactDetailsAriaLabel": "Coordonn\u00e9es de {0}",
    "ContactActionsAriaLabel": "Actions de contact",
    "ChatTitle": "Discuter dans Microsoft Teams",
    "EmailTitle": "Envoyer un e-mail",
    "CallTitle": "Appel audio dans Microsoft Teams",
    "ChatLabel": "Chat",
    "EmailLabel": "E-mail",
    "CallLabel": "Appel",

    "ContactInfoSection": "Coordonn\u00e9es",
    "EmailFieldLabel": "E-mail",
    "WorkPhoneFieldLabel": "T\u00e9l\u00e9phone professionnel",
    "MobileFieldLabel": "Mobile",
    "WorkLocationFieldLabel": "Lieu de travail",

    "OrganizationSection": "Organisation",
    "ManagerLabel": "Responsable",

    "CopiedFeedback": "Copi\u00e9\u00a0!",
    "CopyEmailAriaLabel": "Copier l\u2019adresse e-mail",
    "CopyWorkPhoneAriaLabel": "Copier le t\u00e9l\u00e9phone professionnel",
    "CopyMobileAriaLabel": "Copier le num\u00e9ro de mobile",
    "CopyLocationAriaLabel": "Copier le lieu de travail",

    "TeamsAccessPendingTitle": "Microsoft Teams pas encore configur\u00e9",
    "TeamsAccessPendingMessage": "Votre acc\u00e8s invit\u00e9 \u00e0 Microsoft Teams dans cette organisation n\u2019a pas encore \u00e9t\u00e9 configur\u00e9. Votre propre compte Teams n\u2019est pas concern\u00e9. Demandez \u00e0 votre sponsor de vous ajouter \u00e0 une \u00e9quipe \u2014 ensuite, les fonctionnalit\u00e9s Teams telles que le chat, les appels et les r\u00e9unions seront disponibles ici.",
    "TeamsNotReadyChatTooltip": "Chat non disponible ici \u2014 votre acc\u00e8s invit\u00e9 Teams n\u2019a pas encore \u00e9t\u00e9 configur\u00e9",
    "TeamsNotReadyCallTooltip": "Appel non disponible ici \u2014 votre acc\u00e8s invit\u00e9 Teams n\u2019a pas encore \u00e9t\u00e9 configur\u00e9",

    "LoadingMessageInformal": "Chargement de tes sponsors\u2026",
    "NoSponsorsMessageInformal": "Aucun sponsor trouv\u00e9 pour ton compte.",
    "SponsorUnavailableMessageInformal": "Ton sponsor/propri\u00e9taire n\u2019est plus disponible. Contacte ton responsable de projet pour qu\u2019un nouveau sponsor/propri\u00e9taire te soit attribu\u00e9.",
    "ErrorMessageInformal": "Impossible de charger les informations sur les sponsors. R\u00e9essaie plus tard.",
    "TeamsAccessPendingMessageInformal": "Ton acc\u00e8s invit\u00e9 \u00e0 Microsoft Teams dans cette organisation n\u2019a pas encore \u00e9t\u00e9 configur\u00e9. Ton propre compte Teams n\u2019est pas concern\u00e9. Demande \u00e0 ton sponsor de t\u2019ajouter \u00e0 une \u00e9quipe \u2014 ensuite, tu pourras utiliser les fonctionnalit\u00e9s Teams comme le chat, les appels et les r\u00e9unions ici.",
    "TeamsNotReadyChatTooltipInformal": "Chat non disponible ici \u2014 ton acc\u00e8s invit\u00e9 Teams n\u2019a pas encore \u00e9t\u00e9 configur\u00e9",
    "TeamsNotReadyCallTooltipInformal": "Appel non disponible ici \u2014 ton acc\u00e8s invit\u00e9 Teams n\u2019a pas encore \u00e9t\u00e9 configur\u00e9",

    "DisplayGroupName": "Affichage",
    "ShowBusinessPhonesFieldLabel": "Afficher le t\u00e9l\u00e9phone professionnel",
    "ShowMobilePhoneFieldLabel": "Afficher le num\u00e9ro de mobile",
    "ShowWorkLocationFieldLabel": "Afficher le lieu de travail",
    "ShowManagerFieldLabel": "Afficher le responsable",
    "UseInformalAddressFieldLabel": "Utiliser le tutoiement (tu)",

    "FunctionGroupName": "Azure Function",
    "FunctionUrlFieldLabel": "URL de l'API des sponsors (Azure Function)",
    "FunctionClientIdFieldLabel": "ID de client de l'API des sponsors (inscription d'application Azure Function)",
    "ProxyStatusChecking": "V\u00e9rification de la Azure Function\u2026",
    "ProxyStatusOk": "Azure Function accessible",
    "ProxyStatusError": "Azure Function inaccessible",
    "ShowSponsorJobTitleFieldLabel": "Afficher le poste du sponsor",
    "ShowManagerJobTitleFieldLabel": "Afficher le poste du responsable",
    "ShowSponsorDepartmentFieldLabel": "Afficher le service du sponsor",
    "ShowManagerDepartmentFieldLabel": "Afficher le service du responsable",
    "DepartmentLabel": "Service",
    "ShowCityFieldLabel": "Afficher la ville",
    "ShowCountryFieldLabel": "Afficher le pays",
    "CityFieldLabel": "Ville",
    "CountryFieldLabel": "Pays",
    "CopyCityAriaLabel": "Copier la ville",
    "CopyCountryAriaLabel": "Copier le pays"
  }
});
