define([], function() {
  return {
    "PropertyPaneDescription": "Configura la web part «Info sponsor ospite».",
    "BasicGroupName": "Impostazioni",
    "TitleFieldLabel": "Titolo",
    "LoadingMessage": "Caricamento degli sponsor in corso…",
    "NoSponsorsTitle": "Nessuno sponsor trovato",
    "NoSponsorsMessage": "Nessuno sponsor trovato per il Suo account.",
    "SponsorUnavailableTitle": "Sponsor non disponibile",
    "SponsorUnavailableMessage": "Il Suo sponsor/proprietario non è più disponibile. Contatti il Suo referente di progetto per richiedere l’assegnazione di un nuovo sponsor/proprietario.",
    "ErrorMessageTitle": "Si è verificato un errore",
    "ErrorMessage": "Impossibile caricare le informazioni sugli sponsor. Riprovi più tardi.",
    "EditModePlaceholder": "Info sponsor ospite — passa alla modalità di visualizzazione per vedere gli sponsor.",
    "GuestOnlyPlaceholder": "Questa web part è visibile solo agli utenti ospiti in modalità di visualizzazione.",
    "MockModeFieldLabel": "Modalità demo (dati simulati)",
    "MockModePlaceholder": "Info sponsor ospite — Modalità demo attiva. Passa alla modalità di visualizzazione per vedere i dati simulati.",
    "MockTeamsUnavailableFieldLabel": "Simula indisponibilità di Teams",

    "PresenceAvailable": "Disponibile",
    "PresenceAvailableIdle": "Disponibile, inattivo",
    "PresenceAway": "Assente",
    "PresenceBeRightBack": "Torno subito",
    "PresenceBusy": "Occupato",
    "PresenceBusyIdle": "Occupato, inattivo",
    "PresenceDoNotDisturb": "Non disturbare",
    "PresenceInAMeeting": "In riunione",
    "PresenceInACall": "In una chiamata",
    "PresencePresenting": "In presentazione",
    "PresenceFocusing": "In modalità focus",
    "PresenceOutOfOffice": "Fuori ufficio",
    "PresenceOutOfOfficeSuffix": ", fuori ufficio",
    "PresenceOffline": "Non in linea",

    "ContactDetailsAriaLabel": "Dettagli di contatto di {0}",
    "ContactActionsAriaLabel": "Azioni di contatto",
    "ChatTitle": "Avvia una chat con {name}",
    "EmailTitle": "Invia un'e-mail a {name}",
    "CallTitle": "Avvia una chiamata audio con {name}",
    "ChatLabel": "Chat",
    "EmailLabel": "E-mail",
    "CallLabel": "Chiama",

    "ContactInfoSection": "Contatto",
    "EmailFieldLabel": "E-mail",
    "WorkPhoneFieldLabel": "Telefono ufficio",
    "MobileFieldLabel": "Cellulare",
    "WorkLocationFieldLabel": "Luogo di lavoro",
    "AddressFieldLabel": "Indirizzo",
    "StreetAddressFieldLabel": "Via",
    "PostalCodeFieldLabel": "CAP",
    "StateFieldLabel": "Stato/regione",

    "OrganizationSection": "Organizzazione",
    "ReportsToSection": "Riporta a",
    "ManagerLabel": "Responsabile",

    "CopiedFeedback": "Copiato!",
    "CopyEmailAriaLabel": "Copia indirizzo e-mail",
    "CopyWorkPhoneAriaLabel": "Copia telefono ufficio",
    "CopyMobileAriaLabel": "Copia numero di cellulare",
    "CopyLocationAriaLabel": "Copia luogo di lavoro",
    "CopyAddressAriaLabel": "Copia indirizzo",
    "CopyStreetAddressAriaLabel": "Copia via",
    "CopyPostalCodeAriaLabel": "Copia CAP",
    "CopyStateAriaLabel": "Copia stato/regione",
    "AddressMapSectionLabel": "Anteprima mappa",
    "AddressMapLoadingLabel": "Caricamento anteprima mappa…",
    "OpenAddressInMapLabel": "Apri nella mappa",

    "TeamsAccessPendingTitle": "Microsoft Teams non ancora configurato",
    "TeamsAccessPendingMessage": "Il Suo accesso ospite a Microsoft Teams in questa organizzazione non è ancora stato configurato. Il Suo account Teams personale non è interessato. Chieda al Suo sponsor di aggiungerLa a un Team — una volta fatto, le funzionalità di Teams come chat, chiamate e riunioni saranno disponibili qui.",
    "TeamsNotReadyChatTooltip": "Chat non disponibile qui — il Suo accesso ospite Teams non è ancora stato configurato",
    "TeamsNotReadyCallTooltip": "Chiamata non disponibile qui — il Suo accesso ospite Teams non è ancora stato configurato",

    "VersionMismatchTitle": "Aggiornamento disponibile",
    "VersionMismatchMessage": "È disponibile un aggiornamento della web part. Chiedere all'amministratore di verificare che la web part e la Funzione di Azure utilizzino la stessa versione.",
    "InsufficientPermissionsTitle": "Autorizzazione necessaria",
    "InsufficientPermissionsMessage": "Impossibile caricare le informazioni sugli sponsor — un'autorizzazione di servizio richiesta non è stata concessa. Contattare l'amministratore IT.",

    "NoSponsorsMessageInformal": "Nessuno sponsor trovato per il tuo account.",
    "SponsorUnavailableMessageInformal": "Il tuo sponsor/proprietario non è più disponibile. Contatta il tuo referente di progetto per richiedere l’assegnazione di un nuovo sponsor/proprietario.",
    "ErrorMessageInformal": "Impossibile caricare le informazioni sugli sponsor. Riprova più tardi.",
    "TeamsAccessPendingMessageInformal": "Il tuo accesso ospite a Microsoft Teams in questa organizzazione non è ancora stato configurato. Il tuo account Teams personale non è interessato. Chiedi al tuo sponsor di aggiungerti a un Team — una volta fatto, le funzionalità di Teams come chat, chiamate e riunioni saranno disponibili qui.",
    "TeamsNotReadyChatTooltipInformal": "Chat non disponibile qui — il tuo accesso ospite Teams non è ancora stato configurato",
    "TeamsNotReadyCallTooltipInformal": "Chiamata non disponibile qui — il tuo accesso ospite Teams non è ancora stato configurato",

    "DisplayGroupName": "Visualizzazione",
    "CardLayoutFieldLabel": "Layout scheda",
    "CardLayoutAutoOption": "Automatico",
    "CardLayoutFullOption": "Completo",
    "CardLayoutCompactOption": "Compatto",
    "ShowBusinessPhonesFieldLabel": "Mostra telefono ufficio",
    "ShowMobilePhoneFieldLabel": "Mostra numero di cellulare",
    "ShowWorkLocationFieldLabel": "Mostra luogo di lavoro",
    "ShowManagerFieldLabel": "Mostra responsabile",
    "UseInformalAddressFieldLabel": "Trattamento informale (tu)",
    "UseInformalAddressHint": "Influisce sui messaggi di stato e sui banner che si rivolgono direttamente all'utente ospite in frasi complete (es. messaggi di errore, avviso di accesso a Teams).",

    "ShowWorkLocationFallbackFieldLabel": "Mostra luogo di lavoro come fallback",
    "LocationDisplayHintGeoWithFallback": "La città e il paese sono combinati in un'unica riga geografica. Il luogo di lavoro viene mostrato solo se non sono disponibili dati su città/paese.",
    "LocationDisplayHintGeoOnly": "La città e il paese sono combinati in un'unica riga geografica. Il luogo di lavoro è nascosto.",
    "LocationDisplayHintOfficeOnly": "Viene mostrato solo il luogo di lavoro. Attiva città e/o paese per mostrare invece una riga geografica.",
    "LocationDisplayHintHidden": "Tutti i campi di posizione e indirizzo sono nascosti.",
    "LocationDisplayHintSeparateRows": "I campi indirizzo attivati vengono combinati in una singola riga cliccabile.",
    "AdvancedDisplayGroupName": "Opzioni di visualizzazione avanzate",
    "ManagerOptionsDisabledHint": "Attiva la visualizzazione del responsabile per configurare i campi specifici del responsabile.",
    "FunctionGroupName": "Azure Function",
    "FunctionUrlFieldLabel": "URL di base (Azure Function)",
    "FunctionClientIdFieldLabel": "ID client API sponsor (registrazione applicazione Azure Function)",
    "ProxyStatusChecking": "Verifica Azure Function in corso…",
    "ProxyStatusOk": "Azure Function raggiungibile",
    "ProxyStatusError": "Azure Function non raggiungibile",
    "AuthorSectionGroupName": "Informazioni sull'editore",
    "AuthorSectionIntro": "Workoho GmbH: consulenza per una collaborazione M365 sicura e scalabile.",
    "AuthorSectionWebsiteLinkLabel": "Contatta Workoho per consulenza",
    "AuthorSectionConsultingText": "Ti aiutiamo con governance, accesso guest B2B, identità e processi di collaborazione, così il lavoro di squadra resta sicuro, verificabile ed efficiente.",
    "AuthorSectionPartnerPrefix": "Workoho è",
    "AuthorSectionPartnerLinkLabel": "EasyLife 365",
    "AuthorSectionPartnerSuffix": "partner di vendita Platinum.",
    "AuthorSectionPartnerTagline": "Con EasyLife 365 automatizzi i flussi di accesso e porti ordine negli ambienti Microsoft 365 complessi.",
    "AuthorSectionSourceCodeLabel": "Codice sorgente su GitHub",
    "AuthorSectionVersionLabel": "Versione della web part",
    "ShowSponsorJobTitleFieldLabel": "Mostra il ruolo dello sponsor",
    "ShowManagerJobTitleFieldLabel": "Mostra il ruolo del responsabile",
    "ShowSponsorDepartmentFieldLabel": "Mostra il reparto dello sponsor",
    "ShowManagerDepartmentFieldLabel": "Mostra il reparto del responsabile",
    "DepartmentLabel": "Reparto",
    "ShowCityFieldLabel": "Mostra città",
    "ShowCountryFieldLabel": "Mostra paese",
    "ShowStreetAddressFieldLabel": "Mostra via",
    "ShowPostalCodeFieldLabel": "Mostra CAP",
    "ShowStateFieldLabel": "Mostra stato/regione",
    "AzureMapsSubscriptionKeyFieldLabel": "Chiave sottoscrizione Azure Maps",
    "ExternalMapProviderFieldLabel": "Provider mappa",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "MapProviderNoneOption": "Disattivato (nessun link mappa)",
    "AddressMapProviderHint": "Perché la mappa possa trovare la posizione, attiva almeno la città o il paese insieme agli altri campi dell’indirizzo.",
    "CityFieldLabel": "Città",
    "CountryFieldLabel": "Paese",
    "CopyCityAriaLabel": "Copia città",
    "CopyCountryAriaLabel": "Copia paese",
    "ShowPresenceFieldLabel": "Mostra stato di presenza",
    "ShowSponsorPhotoFieldLabel": "Mostra foto dello sponsor",
    "ShowManagerPhotoFieldLabel": "Mostra foto del responsabile",
  }
});
