define([], function() {
  return {
    "PropertyPaneDescription": "Konfigurer webdelen Gjestesponsorinformasjon.",
    "BasicGroupName": "Innstillinger",
    "TitleFieldLabel": "Tittel",
    "LoadingMessage": "Laster inn sponsorene dine\u2026",
    "NoSponsorsMessage": "Ingen sponsorer ble funnet for kontoen din.",
    "SponsorUnavailableMessage": "Din sponsor/eier er ikke lenger tilgjengelig. Kontakt din prosjektansvarlige for \u00e5 f\u00e5 tildelt en ny sponsor/eier til kontoen din.",
    "ErrorMessage": "Kunne ikke laste inn sponsorinformasjon. Pr\u00f8v igjen senere.",
    "EditModePlaceholder": "Gjestesponsorinformasjon \u2014 bytt til visningsmodus for \u00e5 se sponsorer.",
    "GuestOnlyPlaceholder": "Denne webdelen er bare synlig for gjestebrugere i visningsmodus.",
    "MockModeFieldLabel": "Demonstrasjonsmodus (testdata)",
    "MockModePlaceholder": "Gjestesponsorinformasjon \u2014 Demonstrasjonsmodus aktiv. Bytt til visningsmodus for \u00e5 se testdata.",

    "PresenceAvailable": "Tilgjengelig",
    "PresenceAvailableIdle": "Tilgjengelig, inaktiv",
    "PresenceAway": "Borte",
    "PresenceBeRightBack": "Straks tilbake",
    "PresenceBusy": "Opptatt",
    "PresenceBusyIdle": "Opptatt, inaktiv",
    "PresenceDoNotDisturb": "Ikke forstyrr",
    "PresenceInAMeeting": "I et m\u00f8te",
    "PresenceInACall": "I en samtale",
    "PresencePresenting": "Presenterer",
    "PresenceFocusing": "Fokuserer",
    "PresenceOutOfOffice": "Utenfor kontoret",
    "PresenceOutOfOfficeSuffix": ", utenfor kontoret",
    "PresenceOffline": "Frakoblet",

    "ContactDetailsAriaLabel": "Kontaktdetaljer for {0}",
    "ContactActionsAriaLabel": "Kontakthandlinger",
    "ChatTitle": "Chat i Microsoft Teams",
    "EmailTitle": "Send e-post",
    "CallTitle": "Lydsamtale i Microsoft Teams",
    "ChatLabel": "Chat",
    "EmailLabel": "E-post",
    "CallLabel": "Ring",

    "ContactInfoSection": "Kontaktinformasjon",
    "EmailFieldLabel": "E-post",
    "WorkPhoneFieldLabel": "Jobbtelefon",
    "MobileFieldLabel": "Mobil",
    "WorkLocationFieldLabel": "Arbeidssted",

    "OrganizationSection": "Organisasjon",
    "ManagerLabel": "Leder",

    "CopiedFeedback": "Kopiert!",
    "CopyEmailAriaLabel": "Kopier e-postadresse",
    "CopyWorkPhoneAriaLabel": "Kopier jobbtelefon",
    "CopyMobileAriaLabel": "Kopier mobilnummer",
    "CopyLocationAriaLabel": "Kopier arbeidssted",

    "TeamsAccessPendingTitle": "Microsoft Teams er ikke konfigurert enn\u00e5",
    "TeamsAccessPendingMessage": "Gjestetilgangen din til Microsoft Teams i denne organisasjonen er ikke konfigurert enn\u00e5. Din egen Teams-konto er ikke ber\u00f8rt. Be sponsoren din om \u00e5 legge deg til i et team \u2014 deretter kan du bruke Teams-funksjoner som chat, samtaler og m\u00f8ter her.",
    "TeamsNotReadyChatTooltip": "Chat ikke tilgjengelig her \u2014 Teams-gjestetilgangen din er ikke konfigurert enn\u00e5",
    "TeamsNotReadyCallTooltip": "Samtale ikke tilgjengelig her \u2014 Teams-gjestetilgangen din er ikke konfigurert enn\u00e5",

    "DisplayGroupName": "Visning",
    "ShowBusinessPhonesFieldLabel": "Vis jobbtelefonnumre",
    "ShowMobilePhoneFieldLabel": "Vis mobilnummer",
    "ShowWorkLocationFieldLabel": "Vis arbeidssted",
    "ShowManagerFieldLabel": "Vis leder",
    "UseInformalAddressFieldLabel": "Uformell tiltaleform",

    "FunctionGroupName": "Azure-funksjon",
    "FunctionUrlFieldLabel": "Sponsor-API-URL (Azure-funksjon)",
    "FunctionClientIdFieldLabel": "Sponsor-API-klient-ID (Azure Function-appregistrering)",
    "ProxyStatusChecking": "Sjekker Azure-funksjon\u2026",
    "ProxyStatusOk": "Azure-funksjon er tilgjengelig",
    "ProxyStatusError": "Azure-funksjon er ikke tilgjengelig",
    "ShowSponsorJobTitleFieldLabel": "Vis sponsors stillingstittel",
    "ShowManagerJobTitleFieldLabel": "Vis lederens stillingstittel",
    "ShowSponsorDepartmentFieldLabel": "Vis sponsors avdeling",
    "ShowManagerDepartmentFieldLabel": "Vis lederens avdeling",
    "DepartmentLabel": "Avdeling",
    "ShowCityFieldLabel": "Vis by",
    "ShowCountryFieldLabel": "Vis land",
    "CityFieldLabel": "By",
    "CountryFieldLabel": "Land",
    "CopyCityAriaLabel": "Kopier by",
    "CopyCountryAriaLabel": "Kopier land"
  }
});
