define([], function() {
  return {
    "PropertyPaneDescription": "Configureer het webonderdeel Gastsponsors.",
    "BasicGroupName": "Instellingen",
    "TitleFieldLabel": "Titel",
    "LoadingMessage": "Sponsors worden geladen\u2026",
    "NoSponsorsMessage": "Er zijn geen sponsors gevonden voor uw account.",
    "SponsorUnavailableMessage": "Uw sponsor/eigenaar is niet langer beschikbaar. Neem contact op met uw projectverantwoordelijke om een nieuwe sponsor/eigenaar aan uw account te koppelen.",
    "ErrorMessage": "Kan sponsorinformatie niet laden. Probeer het later opnieuw.",
    "EditModePlaceholder": "Gastsponsors \u2014 schakel over naar de weergavemodus om sponsors te zien.",
    "GuestOnlyPlaceholder": "Dit webonderdeel is alleen zichtbaar voor gastgebruikers in de weergavemodus.",
    "MockModeFieldLabel": "Demomodus (testgegevens)",
    "MockModePlaceholder": "Gastsponsors \u2014 Demomodus actief. Schakel over naar de weergavemodus om testgegevens te zien.",

    "PresenceAvailable": "Beschikbaar",
    "PresenceAvailableIdle": "Beschikbaar, inactief",
    "PresenceAway": "Afwezig",
    "PresenceBeRightBack": "Zo terug",
    "PresenceBusy": "Bezet",
    "PresenceBusyIdle": "Bezet, inactief",
    "PresenceDoNotDisturb": "Niet storen",
    "PresenceInAMeeting": "In een vergadering",
    "PresenceInACall": "In gesprek",
    "PresencePresenting": "Aan het presenteren",
    "PresenceFocusing": "Focusmodus",
    "PresenceOutOfOffice": "Niet op kantoor",
    "PresenceOutOfOfficeSuffix": ", niet op kantoor",
    "PresenceOffline": "Offline",

    "ContactDetailsAriaLabel": "Contactgegevens voor {0}",
    "ContactActionsAriaLabel": "Contactacties",
    "ChatTitle": "Chatten in Microsoft Teams",
    "EmailTitle": "E-mail verzenden",
    "CallTitle": "Audiogesprek in Microsoft Teams",
    "ChatLabel": "Chat",
    "EmailLabel": "E-mail",
    "CallLabel": "Bellen",

    "ContactInfoSection": "Contactgegevens",
    "EmailFieldLabel": "E-mail",
    "WorkPhoneFieldLabel": "Zakelijk telefoonnummer",
    "MobileFieldLabel": "Mobiel",
    "WorkLocationFieldLabel": "Werklocatie",

    "OrganizationSection": "Organisatie",
    "ManagerLabel": "Manager",

    "CopiedFeedback": "Gekopieerd!",
    "CopyEmailAriaLabel": "E-mailadres kopi\u00ebren",
    "CopyWorkPhoneAriaLabel": "Zakelijk telefoonnummer kopi\u00ebren",
    "CopyMobileAriaLabel": "Mobiel nummer kopi\u00ebren",
    "CopyLocationAriaLabel": "Werklocatie kopiëren",

    "TeamsAccessPendingTitle": "Microsoft Teams is nog niet ingesteld",
    "TeamsAccessPendingMessage": "Uw gasttoegang tot Microsoft Teams in deze organisatie is nog niet ingesteld. Uw eigen Teams-account wordt hierdoor niet be\u00efnvloed. Vraag uw sponsor om u toe te voegen aan een team \u2014 daarna kunt u hier Teams-functies zoals chat, bellen en vergaderingen gebruiken.",
    "TeamsNotReadyChatTooltip": "Chat hier niet beschikbaar \u2014 uw Teams-gasttoegang is nog niet ingesteld",
    "TeamsNotReadyCallTooltip": "Bellen hier niet beschikbaar \u2014 uw Teams-gasttoegang is nog niet ingesteld",

    "NoSponsorsMessageInformal": "Er zijn geen sponsors gevonden voor je account.",
    "SponsorUnavailableMessageInformal": "Je sponsor/eigenaar is niet langer beschikbaar. Neem contact op met je projectverantwoordelijke om een nieuwe sponsor/eigenaar aan je account te koppelen.",
    "TeamsAccessPendingMessageInformal": "Je gasttoegang tot Microsoft Teams in deze organisatie is nog niet ingesteld. Je eigen Teams-account wordt hierdoor niet be\u00efnvloed. Vraag je sponsor om je toe te voegen aan een team \u2014 daarna kun je hier Teams-functies zoals chat, bellen en vergaderingen gebruiken.",
    "TeamsNotReadyChatTooltipInformal": "Chat hier niet beschikbaar \u2014 je Teams-gasttoegang is nog niet ingesteld",
    "TeamsNotReadyCallTooltipInformal": "Bellen hier niet beschikbaar \u2014 je Teams-gasttoegang is nog niet ingesteld",

    "DisplayGroupName": "Weergave",
    "ShowBusinessPhonesFieldLabel": "Zakelijk telefoonnummer weergeven",
    "ShowMobilePhoneFieldLabel": "Mobiel nummer weergeven",
    "ShowWorkLocationFieldLabel": "Werklocatie weergeven",
    "ShowManagerFieldLabel": "Manager weergeven",
    "UseInformalAddressFieldLabel": "Informeel aanspreken (jij/je)",

    "FunctionGroupName": "Azure-functie",
    "FunctionUrlFieldLabel": "Sponsor API-URL (Azure-functie)",
    "FunctionClientIdFieldLabel": "Sponsor API-client-ID (Azure-functie-app-registratie)",
    "ProxyStatusChecking": "Azure Function controleren\u2026",
    "ProxyStatusOk": "Azure Function bereikbaar",
    "ProxyStatusError": "Azure Function niet bereikbaar"
  }
});
