define([], function() {
  return {
    "PropertyPaneDescription": "Skonfiguruj sk\u0142adnik Web Part Informacje o sponsorze go\u015bcia.",
    "BasicGroupName": "Ustawienia",
    "TitleFieldLabel": "Tytu\u0142",
    "LoadingMessage": "\u0141adowanie sponsor\u00f3w\u2026",
    "NoSponsorsMessage": "Nie znaleziono sponsor\u00f3w dla Twojego konta.",
    "SponsorUnavailableMessage": "Tw\u00f3j sponsor/w\u0142a\u015bciciel nie jest ju\u017c dost\u0119pny. Skontaktuj si\u0119 z odpowiedzialn\u0105 osob\u0105 w projekcie, aby przypisano nowego sponsora/w\u0142a\u015bciciela do Twojego konta.",
    "ErrorMessage": "Nie mo\u017cna za\u0142adowa\u0107 informacji o sponsorze. Spr\u00f3buj ponownie p\u00f3\u017aniej.",
    "EditModePlaceholder": "Informacje o sponsorze go\u015bcia \u2014 prze\u0142\u0105cz do trybu wy\u015bwietlania, aby zobaczy\u0107 sponsor\u00f3w.",
    "GuestOnlyPlaceholder": "Ten sk\u0142adnik Web Part jest widoczny tylko dla u\u017cytkownik\u00f3w-go\u015bci w trybie wy\u015bwietlania.",
    "MockModeFieldLabel": "Tryb demonstracyjny (dane testowe)",
    "MockModePlaceholder": "Informacje o sponsorze go\u015bcia \u2014 aktywny tryb demonstracyjny. Prze\u0142\u0105cz do trybu wy\u015bwietlania, aby zobaczy\u0107 dane testowe.",

    "PresenceAvailable": "Dost\u0119pny",
    "PresenceAvailableIdle": "Dost\u0119pny, bezczynny",
    "PresenceAway": "Nieobecny",
    "PresenceBeRightBack": "Zaraz wr\u00f3ci",
    "PresenceBusy": "Zaj\u0119ty",
    "PresenceBusyIdle": "Zaj\u0119ty, bezczynny",
    "PresenceDoNotDisturb": "Nie przeszkadza\u0107",
    "PresenceInAMeeting": "Na spotkaniu",
    "PresenceInACall": "W trakcie rozmowy",
    "PresencePresenting": "Prezentuje",
    "PresenceFocusing": "W trybie skupienia",
    "PresenceOutOfOffice": "Poza biurem",
    "PresenceOutOfOfficeSuffix": ", poza biurem",
    "PresenceOffline": "Offline",

    "ContactDetailsAriaLabel": "Dane kontaktowe dla {0}",
    "ContactActionsAriaLabel": "Akcje kontaktowe",
    "ChatTitle": "Czat w Microsoft Teams",
    "EmailTitle": "Wy\u015blij e-mail",
    "CallTitle": "Po\u0142\u0105czenie audio w Microsoft Teams",
    "ChatLabel": "Czat",
    "EmailLabel": "E-mail",
    "CallLabel": "Zadzwo\u0144",

    "ContactInfoSection": "Informacje kontaktowe",
    "EmailFieldLabel": "E-mail",
    "WorkPhoneFieldLabel": "Telefon s\u0142u\u017cbowy",
    "MobileFieldLabel": "Telefon kom\u00f3rkowy",
    "WorkLocationFieldLabel": "Lokalizacja miejsca pracy",

    "OrganizationSection": "Organizacja",
    "ManagerLabel": "Mened\u017cer",

    "CopiedFeedback": "Skopiowano!",
    "CopyEmailAriaLabel": "Kopiuj adres e-mail",
    "CopyWorkPhoneAriaLabel": "Kopiuj telefon s\u0142u\u017cbowy",
    "CopyMobileAriaLabel": "Kopiuj numer telefonu kom\u00f3rkowego",
    "CopyLocationAriaLabel": "Kopiuj lokalizację miejsca pracy",

    "TeamsAccessPendingTitle": "Microsoft Teams nie zosta\u0142 jeszcze skonfigurowany",
    "TeamsAccessPendingMessage": "Tw\u00f3j dost\u0119p go\u015bcia do Microsoft Teams w tej organizacji nie zosta\u0142 jeszcze skonfigurowany. Twoje w\u0142asne konto Teams nie jest tym dotkni\u0119te. Popro\u015b swojego sponsora o dodanie Ci\u0119 do zespo\u0142u \u2014 po tym funkcje Teams, takie jak czat, po\u0142\u0105czenia i spotkania, b\u0119d\u0105 dost\u0119pne tutaj.",
    "TeamsNotReadyChatTooltip": "Czat niedost\u0119pny w tej organizacji \u2014 Tw\u00f3j dost\u0119p go\u015bcia Teams nie zosta\u0142 jeszcze skonfigurowany",
    "TeamsNotReadyCallTooltip": "Po\u0142\u0105czenie niedost\u0119pne w tej organizacji \u2014 Tw\u00f3j dost\u0119p go\u015bcia Teams nie zosta\u0142 jeszcze skonfigurowany",

    "DisplayGroupName": "Wy\u015bwietlanie",
    "ShowBusinessPhonesFieldLabel": "Poka\u017c telefon s\u0142u\u017cbowy",
    "ShowMobilePhoneFieldLabel": "Poka\u017c numer telefonu kom\u00f3rkowego",
    "ShowWorkLocationFieldLabel": "Poka\u017c lokalizacj\u0119 miejsca pracy",
    "ShowManagerFieldLabel": "Poka\u017c mened\u017cera",
    "UseInformalAddressFieldLabel": "Forma nieformalna (ty)",

    "FunctionGroupName": "Azure Function",
    "FunctionUrlFieldLabel": "Adres URL interfejsu API sponsorów (Azure Function)",
    "FunctionClientIdFieldLabel": "Identyfikator klienta interfejsu API sponsor\u00f3w (rejestracja aplikacji Azure Function)",
    "ProxyStatusChecking": "Sprawdzanie Azure Function\u2026",
    "ProxyStatusOk": "Azure Function osi\u0105galna",
    "ProxyStatusError": "Azure Function nieosi\u0105galna"
  }
});
